# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Smh
                                 A QGIS plugin
 connect to a postreSql and load the data to Qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-06
        copyright            : (C) 2024 by hamza bouhali
        email                : bouhali.hamza.2@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Smh class from file Smh.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .smh_plugin import Smh
    return Smh(iface)
